version: '3'
services:
  connector-02:
    image: linker.spendzer.com/connector:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
      domainName: domain-01
      connectorName: connector-02
    ports:
      - "8088:8088"
  processor-02:
    image: linker.spendzer.com/processor:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
      domainName: domain-01
      processorName: processor-02