version: '3'
services:
  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-host
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  nats:
    image: 'nats:latest'
    hostname: 'nats-server'
    ports:
      - "8222:8222"
      - "4222:4222"
  redis:
    image: redis
    ports:
      - "6379:6379"
  connector-02:
    image: linker.spendzer.com/connector:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
      domainName: domain-01
      connectorName: connector-02
    ports:
      - "8088:8088"
    depends_on:
      - rabbit-mq
      - zookeeper
      - kafka
      - nats
  processor-02:
    image: linker.spendzer.com/processor:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
      domainName: domain-01
      processorName: processor-02
    depends_on:
      - rabbit-mq
      - zookeeper
      - kafka
      - nats
      - redis